http:
  routers:
    home-assistant:
      rule: "Host(`home-assistant.lankrui.be`)"
      service: home-assistant-service
      tls:
        certResolver: letsEncrypt

  services:
    home-assistant-service:
      loadBalancer:
        servers:
          - url: "http://192.168.68.51:8123"

