# http:
#   routers:
#     pve:
#       rule: "Host(`pve.lankrui.be`)"
#       entryPoints:
#         - https
#       service: pve-service
#       tls:
#         certResolver: letsEncrypt

#   services:
#     pve-service:
#       loadBalancer:
#         servers:
#           - url: "http://192.168.68.69:8006"