http:
  routers:
    apcupsd:
      rule: "Host(`apcupsd.lankrui.be`)"
      service: apcupsd-service
      tls:
        certResolver: letsEncrypt
      middlewares:
        - authentik

  services:
    apcupsd-service:
      loadBalancer:
        servers:
          - url: "http://192.168.68.69:80/cgi-bin/apcupsd"
            preservePath: true