http:
  routers:
    media-server-portainer:
      rule: "Host(`media-server-portainer.lankrui.be`)"
      entryPoints:
        - https
      service: media-server-portainer-service
      tls:
        certResolver: letsEncrypt

  services:
    media-server-portainer-service:
      loadBalancer:
        servers:
          - url: "http://192.168.68.75:9000"