http:
  routers:
    qbittorrent:
      rule: "Host(`qbittorrent.lankrui.be`)"
      service: qbittorrent-service
      tls:
        certResolver: letsEncrypt
      middlewares:
        - authentik

  services:
    qbittorrent-service:
      loadBalancer:
        servers:
          - url: "http://192.168.68.75:8080"