http:
  routers:
    radarr:
      rule: "Host(`radarr.lankrui.be`)"
      service: radarr-service
      tls:
        certResolver: letsEncrypt
      middlewares:
        - authentik

  services:
    radarr-service:
      loadBalancer:
        servers:
          - url: "http://192.168.68.75:7878"