http:
  routers:
    sabnzbd:
      rule: "Host(`sabnzbd.lankrui.be`)"
      service: sabnzbd-service
      tls:
        certResolver: letsEncrypt
      middlewares:
        - authentik

  services:
    sabnzbd-service:
      loadBalancer:
        servers:
          - url: "http://192.168.68.75:8081"