http:
  routers:
    sonarr:
      rule: "Host(`sonarr.lankrui.be`)"
      service: sonarr-service
      tls:
        certResolver: letsEncrypt
      middlewares:
        - authentik

  services:
    sonarr-service:
      loadBalancer:
        servers:
          - url: "http://192.168.68.75:8989"