entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  letsEncrypt:
    acme:
      email: robin.landerloos@outlook.com
      storage: "/certs/acme.json"
      dnsChallenge:
        provider: cloudflare  
        delayBeforeCheck: 0  

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true
  insecure: true 

log:
  filePath: "/logs/traefik.log"
  level: "DEBUG"
